---
- name: Create devops network
  docker_network:
    name: devops_network

- name: Create Jenkins container
  docker_container:
    name: myjenkins
    image: "jenkins/jenkins:lts"
    volumes:
      - /opt/jenkins_home:/var/jenkins_home
    ports:
      - "8180:8080"
      - "51000:50000"
    networks:
      - name: devops_network

- name: Create SonarQube container
  docker_container:
    name: mysonar
    image: "sonarqube:lts"
    ports:
      - "9000:9000"
    networks:
      - name: devops_network