---
- name: Create devops network
  docker_network:
    name: devops_network

- name: Create Jenkins container
  docker_container:
    name: myjenkins
    image: "jenkins/jenkins:lts"
    volumes:
      - /home/sylvioneto/Downloads/cursos/devops_jenkins/jenkins_home:/var/jenkins_home
    ports:
      - "8180:8080"
      - "51000:50000"
    networks:
      - name: devops_network